- package.json
Using Node 9.x is perfectly fine for example. As I don't see any value of having such thing in the dependencies, I propose to remove them :)
> Remove engines from the dependency requirements

- CHANGELOG.md
- assets/quill-cursors.scss
- example/index.html
- example/styles.css
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
Fixes https://github.com/reedsy/quill-cursors/issues/14
If a Quill container has fixed height, then the editor scrolls.
However, there are currently two issues with the cursor behaviour when
this happens:
- the cursors and selections will appear outside the editor
- the selections do not update when scrolling the editor
This change addresses the above issues by:
- setting `overflow: hidden` on `.ql-container` to hide the cursors
when they overflow the editor
- adding a `scroll` listener to the `.ql-editor`, which will trigger
a cursor position update
> Fix cursor behaviour for Quill containers with fixed height

- CHANGELOG.md
- README.md
- src/quill-cursors/cursor.spec.ts
- src/quill-cursors/cursor.ts
- src/quill-cursors/i-quill-cursors-options.ts
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
Sometimes it can be useful to adjust the CSS class attached to the
cursor container. For example, when using multiple cursor modules on the
same document.
This change adds an option to add a custom CSS class to the container.
It also adds an `id` attribute to each container, in case you want to
target a particular cursor through either CSS or JavaScript.
> Add the cursor ID and a custom CSS class to the cursor container

- CHANGELOG.md
- package.json
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
We currently listen for `resize` events fired on the window to redraw
the cursors.
However, this approach misses the event where the editor is resized for
other reasons (such as through JavaScript), without the window being
resized.
Ideally, we'd use the new [`ResizeObserver`][1] class, but this is
restricted just to Chrome for now. Instead, we're using a [polyfill][2].
[1]: https://developers.google.com/web/updates/2016/10/resizeobserver
[2]: https://github.com/pelotoncycle/resize-observer
> Use `ResizeObserver` instead of listening for window `resize` event

- CHANGELOG.md
- package.json
- src/quill-cursors/cursor.spec.ts
- src/quill-cursors/cursor.ts
- src/quill-cursors/quill-cursors.spec.ts
Fixes https://github.com/reedsy/quill-cursors/issues/29
At the moment, the `span` elements that make up a multi-line selection
are not necessarily added in the correct "order" (ie from top-left to
bottom-right of the document). Sometimes we may want these in order so
that we can style them using CSS selectors like `:first-child`.
This works by accident currently in Chrome, but not in Firefox. This
change actively sorts the `span` elements by their rectangles from
top-to-bottom, and then left-to-right. Note that we ignore right-to-left
text as out-of-scope for this change.
> Add selection `span` elements in order

- CHANGELOG.md
- src/quill-cursors/cursor.spec.ts
- src/quill-cursors/cursor.ts
If the user's selection contains some formatted text, the selection can
contain overlapping rectangles, which leads to a selection with varying
opacity.
This change checks for these identical rectangles and deduplicates them.
> Deduplicate perfectly overlapping client rectangles

- CHANGELOG.md
- assets/quill-cursors.scss
Fixes https://github.com/reedsy/quill-cursors/issues/32
At the moment, when we add a selection using `span` elements, they
appear further down the DOM, and hence are put "on top" of the editor
text. In other words, if another user has highlighted some text, then
their selection will prevent me from placing my cursor inside it.
This change moves the selection behind the text with a `z-index: -1`,
which avoids intercepting the click on the editor. It should be noted
that this will also hide the selections if a background is applied to
the editor, but fixing that case is left to the consumer.
> Move selection behind text

- CHANGELOG.md
- src/quill-cursors/cursor.spec.ts
- src/quill-cursors/cursor.ts
Sometimes selection rectangles can come back with zero height or zero
width. In these cases, we should just ignore the rectangle.
> Ignore zero-height and zero-width selection rectangles

- CHANGELOG.md
- assets/quill-cursors.scss
We previously set the selections' `z-index: -1` to avoid the selections
blocking click events. However, this doesn't work on block-level
elements, such as `image-block`s, because the selection is perfectly
behind the image.
This change removes the `z-index` assignment, and we instead let the
selections remain on top, but we apply `pointer-events: none` to avoid
the selections reacting to `click` or `touch` events.
> Use pointer-events: none for selections

- CHANGELOG.md
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
Fixes https://github.com/reedsy/quill-cursors/issues/35
We currently build a selection from a single `Range` object, which can
contain a mixture of `inline` and `block` elements. In particular, with
paragraphs, the behaviour between browsers is inconsistent.
For example, when selecting an entire paragraph, Chrome will draw
rectangles around each line in the paragraph, as well as a big rectangle
around the `<p>` element itself. Firefox, on the other hand, will only
draw a rectangle around the `<p>` block, but not the individual lines.
Both of these behaviours are different still to how the browser's
built-in "selection" looks (ie just drawing rectangles around the
individual lines, and never the `<p>` element).
In order to simulate this more "natural" selection behaviour, this
change leans …
> Build selection from multiple Ranges

- CHANGELOG.md
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
When we try to highlight a range, we first attempt to normalise it to
within Quill's bounds. However, the upper limit we apply is the length
of the Quill document, when actually - because Quill is zero-indexed -
we should set the upper limit to `quill.getLength() - 1`.
This change updates our upper limit so that we avoid getting errors when
attempting to set the selection outside the allowable range.
> Fix max Quill index

- CHANGELOG.md
- README.md
- example/main.js
- package.json
- src/quill-cursors/i-quill-cursors-options.ts
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
- typings/quill-delta.d.ts
Fixes https://github.com/reedsy/quill-cursors/issues/25
At the moment, we have to wait for clients to report their position
before we update it. This is fine on very low-latency connections (like
when developing on the same machine), but on high-latency connections,
it can lead to some laggy or juddery performance as the cursor drifts
out-of-sync with the `text-change` events received by Quill:
This change adds in a `text-change` listener that will transform all
cursors by the received delta using `quill-delta`'s `transformPosition`,
which is meant for exactly this sort of application.
The example has also been updated to show how a cursor implementation
might look on a high-latency connection, using a debounced update to
avoid laggy behaviour.
> Add local cursor transforms on `text-change`

- CHANGELOG.md
- src/quill-cursors/cursor.ts
Fixes https://github.com/reedsy/quill-cursors/issues/45
When setting an element's `innerHTML` to `null`, Internet Explorer will
render this as a ["null" text node][1]. This change instead replaces the
contents with an empty string, which should be rendered correctly
across all browsers.
[1]: https://github.com/reedsy/quill-cursors/issues/45
> Fix `null` being rendered on clear

- CHANGELOG.md
- README.md
- assets/quill-cursors.scss
- src/quill-cursors/cursor.spec.ts
- src/quill-cursors/cursor.ts
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
This change adds a feature to address a couple of pull requests that
have come up wanting the ability to control flag display:
- https://github.com/reedsy/quill-cursors/pull/41
- https://github.com/reedsy/quill-cursors/pull/48
Both of the above cases want slightly different behaviour, so this
change does the minimum work to satisfy both (ie allow control of
whether a cursor's flag is displayed), whilst also keeping our API
surface small.
> Allow manually showing and hiding flags

- CHANGELOG.md
- assets/quill-cursors.scss
- src/quill-cursors/cursor.spec.ts
- src/quill-cursors/cursor.ts
This change updates our new flag toggling logic so that if a flag is
actively toggled, it is hidden immediately (ignoring the configured
`hideDelayMs` option). The hide delay should still apply in the hover
case.
We achieve this by adding a `.no-delay` class to the flag when we toggle
it, which suppresses the `transition-delay`. We have then wait for the
animation to complete before removing it again, so that the flag still
behaves as configured on hover.
> Hide flag immediately when actively toggling

- CHANGELOG.md
- assets/quill-cursors.scss
This change removes virtually all the styling we do on the "core" Quill
elements, in order to remain as unopinionated as possible.
We explicitly add `position: relative`, which technically isn't needed,
because it's included in Quill's default stylings. However, people are
free to ignore Quill's default stylings, or the styling could be removed
altogether, in which case our `absolute` positioning would break, so
let's explicitly set this just to be safe.
The one exception we have to make is that we need to set
`overflow: hidden` on `.ql-container`, which fixes the issue of
selections appearing outside an editor with a fixed height:
https://github.com/reedsy/quill-cursors/pull/21
Note that this should be acceptable, because even Quill's Bubble theme
displays poor behaviour in this case, so …
> Breaking: Remove core Quill styling

- CHANGELOG.md
- package.json
- src/index.ts
- tsconfig.json
Because sources written in typescript it worth nothing to output original declation files.
Typescript users (I am among them) will be happy!
> Output typescript declaration files

- assets/quill-cursors.scss
- src/quill-cursors/cursor.spec.ts
- src/quill-cursors/cursor.ts
- src/quill-cursors/i-quill-cursors-options.ts
- src/quill-cursors/quill-cursors.ts
- src/quill-cursors/template.ts
When the cursor is on the first line the flag can be clipped by container top bound. Same can happen when cursor is near the right edge of the container.
This PR tries to always show it unclipped.
Vertically it shows flag under the cursor if it can't be fit above it.
Horizontally it shifts flag to the left to fit it completely.
PS. I'll add tests and fix other issues if overall PR is ok and acceptable.
> Always try to fit cursor flag into container

- CHANGELOG.md
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
Fixes https://github.com/reedsy/quill-cursors/issues/57
This change fixes a bug that can be reproduced by:
1. Run the development app
2. Paste an image into the editor
3. Select all
4. The "remote" cursor does not highlight the image, and the console
errors
This is because when using `Range.setStart` and `Range.setEnd`, the
`offset` argument is treated differently for non-text nodes.
This change updates our range definitions to check if the leaf in
question is a text node or not. If it is a text node, then we use the
offset as before. However, if it isn't a text node (eg an `img`), then
we simply set the selection before/after the node using
`Range.setStartBefore` and `Range.setEndAfter`.
> Fix image selection

- CHANGELOG.md
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
Fixes https://github.com/reedsy/quill-cursors/issues/61
At the moment, the `ResizeObserver` causes a memory leak, because we
never unobserve the Quill container, which then keeps a reference to
that node in memory (even if the node is disconnected from the DOM).
This change tweaks our `ResizeObserver` callback to check if the Quill
container is still connected to the DOM. If not, we unobserve, which
allows the `ResizeObserver` and DOM node to both be correctly garbage-
collected.
However, we can't just leave it there, because consumers may potentially
disconnect their Quill instance, and then reconnect it to the DOM. In
order to address this edge case, we re-register the `ResizeObserver`
whenever an update is made to a cursor, which should start listening
correctly the next time any …
> ⚡️ Fix `ResizeObserver` memory leak

- CHANGELOG.md
- src/quill-cursors/quill-cursors.ts
Quill's [`Module` class][1] has a number of properties defined on it,
which the `QuillCursors` module doesn't expose.
This can make it tricky when trying to write generic type definitions
involving modules, since this module doesn't conform to the expected
interface.
This change aligns us with the `Module` interface. This also involves
including a static `DEFAULTS` property, which consumers could in theory
override themselves, so here we also populate our default options from
this property.
[1]: https://github.com/quilljs/quill/blob/develop/core/module.js
> 🏷️ Conform to Quill `Module` interface

- .github/workflows/test.yml
- package.json
There is a timeout [issue][1] with installing dependencies. It stucks with `fetchMetadata`.
Changing the Node version fixes it.
Additionally, I removed unused `extract-text-webpack-plugin`, which produced conflict webpack version errors
[1]: https://github.com/reedsy/quill-cursors/runs/7019331689
> 👷 Fix broken actions

- CHANGELOG.md
- assets/quill-cursors.scss
- package.json
- src/quill-cursors/cursor.spec.ts
- src/quill-cursors/cursor.ts
- src/quill-cursors/i-coordinates.ts
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
There is the issue with using CSS for opening/closing logic for flags. It's broken on touch devices (which don't trigger the `:hover` styling) (Issue #77). To fix it, we moved all the logic to JS:
- Changed `z-index` to «move» a cursor behind the text. It resolves the issue, when a cursor prevent clicking on the text (even if a user clicks exactly on cursor)
- Added listeners for `mousemove` and `touchstart` with a callback, which shows/closes flags depends on a point position
To achieve it there are added a couple of callbacks to update cursors position and store it in the quill-cursors module. It should be enough to cover all cases for touch and non-touch devices. Also, there is a small throttling for mousemove events to improve performance and decrease amount of callbacks executions
> ♻️ Change flag opening/closing logic

- package.json
Upstream changes to `@typescript-eslint` broke the config for our `eslint-config-reedsy` library.
We actually deprecated that library in favour of `@reedsy/eslint-plugin` but that package is currently private.
Until we sort out permissions, this change quickly just pins our version of `@typescript-eslint` to greenify the build.
> 📌 Pin `@typescript-eslint`

- CHANGELOG.md
- package.json
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
After the last Chrome's update to version 109, there is the issue with `ResizeObserver limit loop`, because of infinity loop. It happens because we **always** update cursors, which registers the new observer. Let's return from the function and prevent creating new observer for cases, when it should stop observing
> 🐛 Fix ResizeObserver limit loop

- src/quill-cursors/cursor.ts
- src/quill-cursors/quill-cursors.spec.ts
- src/quill-cursors/quill-cursors.ts
Fixes https://github.com/reedsy/quill-cursors/issues/92
If an event listener never invokes `preventDefault()`, it can be marked as [passive][1].
We don't call `preventDefault()` anywhere in our code, so we can safely mark all of our event listeners as passive.
[1]: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#using_passive_listeners
> ⚡️ Make all event listeners passive
